name: Per Minute Workflow

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout code
      #  uses: NarendraSG/starter-express-api@main
        
      - name: Init
        run: |
          for i in {1..10}; do
            echo $i
          done
